"""Regression locks for the CSM squad/character slot migration.

Locks the curated CSM config to the BSData truth (verified 2026-08-13
against the "Chaos - Chaos Space Marines Library" catalogue):

Characters:
- Fabius Bile is a 2-model character unit (Fabius Bile + Surgeon Acolyte,
  100 pts). BSData: Fabius Bile carries Xyclos needler, The Chirurgeon,
  Rod of Torment; the Surgeon Acolyte carries Surgeon Acolyte's tools.
  The OLD squads.json entry gave BOTH models the needler + Chirurgeon and
  dropped Rod of Torment + Acolyte's tools — wrong. The character entry
  carries all four weapons in ONE fixed build.
- Choice weapons MUST reference the GROUP name, never profile suffixes:
  both profile names in fixed double-counts ranged (summed in _ld_dmg),
  and a single profile lock permanently excludes the other profile.
  Fixed this iteration: Dark Commune Warp Curse (was BOTH witchfire +
  focused witchfire = ranged double-count), Heretic Astartes Daemon
  Prince Hellforged weapons (strike only — sweep never scored), Master
  Of Possession Rite of Possession (focused only), Sorcerer/In Terminator
  Armour Infernal Gaze (focused only), Reave-Captain/Warpsmith Plasma
  pistol (standard only — supercharge never scored), Vashtorr's hammer
  (strike+sweep both, melee immune but group name is the clean reference).

Squads (regenerated by gen_squad_composition.py --force):
- alloc pools carry min/max + typed weapon payloads (Legionaries,
  Chosen, Accursed Cultists Torment/Mutant split)
- per-model slots with default-flagged choices (Cultist Mob champion
  pistol)

STRUCTURE ONLY — no damage values. The engine is the single source of
computation; this test locks the config shape and resolvability, not math.

Run: python3 -m pytest tests/test_chaos_space_marines_complex_units.py -v
"""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from engine.ranking import RankingEngine

CONFIG_DIR = Path(__file__).resolve().parent.parent / "data" / "config"
CHARS_PATH = CONFIG_DIR / "chaos-space-marines" / "characters.json"
SQUADS_PATH = CONFIG_DIR / "chaos-space-marines" / "squads.json"

TARGET_SAMPLES = ["GEQ", "MEQ", "TEQ"]

# ── Fabius Bile (2-model character unit) ────────────────────────────────
FABIUS_PTS = 100
FABIUS_WEAPONS = {
    "Xyclos needler", "The Chirurgeon", "Rod of Torment",
    "Surgeon Acolyte's tools",
}

# ── Choice weapons that must reference the GROUP name ────────────────────
CHOICE_GROUPS = {
    "Dark Commune": {"Warp Curse"},
    "Heretic Astartes Daemon Prince": {"Hellforged weapons"},
    "Heretic Astartes Daemon Prince With Wings": {"Hellforged weapons"},
    "Master Of Possession": {"Rite of Possession"},
    "Sorcerer": {"Infernal Gaze"},
    "Sorcerer In Terminator Armour": {"Infernal Gaze"},
    "Red Corsairs Reave-Captain": {"Plasma pistol"},
    "Warpsmith": {"Plasma pistol"},
    "Vashtorr The Arkifane": {"Vashtorr's hammer"},
}

# Profiles that must NEVER appear in fixed (ranged double-count / lock bugs)
FORBIDDEN_PROFILES = [
    "Warp Curse - witchfire", "Warp Curse - focused witchfire",
    "Hellforged weapons - strike", "Hellforged weapons - sweep",
    "Rite of Possession - witchfire", "Rite of Possession - focused witchfire",
    "Infernal Gaze - witchfire", "Infernal Gaze - focused witchfire",
    "Plasma pistol - standard", "Plasma pistol - supercharge",
    "Vashtorr's hammer - strike", "Vashtorr's hammer - sweep",
]


@pytest.fixture(scope="module")
def csm_engine():
    return RankingEngine("chaos-space-marines")


@pytest.fixture(scope="module")
def chars():
    return json.load(open(CHARS_PATH))


@pytest.fixture(scope="module")
def squads():
    return json.load(open(SQUADS_PATH))


def _fixed_names(build) -> set[str]:
    return {f["name"] for f in build.get("fixed", [])}


def _resolve(engine, build, unit_name, target_name="MEQ"):
    """Resolve one build via the engine's slots path -> (ranged, melee) names."""
    r, m, _n = engine._resolve_slots_build(
        build, unit_name, engine.resolve_target(target_name))
    return [w.name for w in r], [w.name for w in m]


class TestFabiusBile:
    """2-model character unit — moved from squads.json to characters.json."""

    def test_in_characters_not_squads(self, chars, squads):
        assert "Fabius Bile" in chars, "Fabius Bile must be a character"
        assert "Fabius Bile" not in squads, "Fabius Bile must NOT be in squads.json"

    def test_pts(self, chars):
        assert chars["Fabius Bile"]["pts"] == FABIUS_PTS

    def test_all_four_weapons_in_one_build(self, chars):
        build = chars["Fabius Bile"]["weapon_options"]["builds"][0]
        fixed = _fixed_names(build)
        assert fixed == FABIUS_WEAPONS, fixed
        assert build["slots"] == []

    def test_resolves_all_targets(self, csm_engine, chars):
        build = chars["Fabius Bile"]["weapon_options"]["builds"][0]
        for t in TARGET_SAMPLES:
            ranged, melee = _resolve(csm_engine, build, "Fabius Bile", t)
            assert any("Xyclos" in n for n in ranged), f"{t}: no Xyclos needler"
            assert len(melee) == 3, f"{t}: expected 3 melee weapons, got {melee}"


class TestChoiceGroups:
    """Choice weapons reference GROUP names — never profile suffixes."""

    def test_no_profile_suffix_in_fixed(self, chars):
        for unit, groups in CHOICE_GROUPS.items():
            build = chars[unit]["weapon_options"]["builds"][0]
            fixed = _fixed_names(build)
            assert groups <= fixed, f"{unit}: missing group {groups - fixed} in {fixed}"
            for fp in FORBIDDEN_PROFILES:
                assert fp not in fixed, f"{unit}: profile suffix leaked: {fp}"

    def test_groups_carry_variants(self, csm_engine):
        """Group reference must resolve to a weapon carrying choice variants."""
        for unit, groups in CHOICE_GROUPS.items():
            for g in groups:
                w = csm_engine.W(g, unit_name=unit)
                assert w.variants, f"{unit}: {g} resolved without variants"

    def test_warp_curse_single_entry(self, chars):
        """The Mindwitch carries ONE Warp Curse weapon — one fixed entry."""
        build = chars["Dark Commune"]["weapon_options"]["builds"][0]
        count = sum(1 for f in build["fixed"] if f["name"] == "Warp Curse")
        assert count == 1, f"Warp Curse appears {count} times in fixed"

    def test_loadouts_resolve(self, csm_engine, chars):
        for unit in CHOICE_GROUPS:
            build = chars[unit]["weapon_options"]["builds"][0]
            for t in TARGET_SAMPLES:
                ranged, melee = _resolve(csm_engine, build, unit, t)
                assert ranged or melee, f"{unit} {t}: empty loadout"


class TestRegeneratedSquads:
    """Generator output structure — alloc pools, slots, defaults."""

    def test_legionaries_alloc_pool(self, squads):
        build = squads["Legionaries"]["builds"][0]
        models = {m["name"]: m for m in build["models"]}
        legionary = models["Legionary"]
        alloc = {a["name"]: a for a in legionary["alloc"]}
        assert legionary["count"] == 4
        assert alloc["Legionary w/ boltgun"]["min"] == 0
        assert alloc["Legionary w/ heavy melee weapon"]["max"] == 1
        assert alloc["Legionary w/ balefire tome"]["max"] == 1
        assert "Boltgun" in alloc["Legionary w/ boltgun"]["ranged"]
        assert alloc["Legionary w/ other weapon"]["slots"][0]["name"] == "Weapon"

    def test_chosen_alloc_pool(self, squads):
        build = squads["Chosen"]["builds"][0]
        chosen = build["models"][0]
        assert chosen["count"] == 5
        names = {a["name"] for a in chosen["alloc"]}
        assert "Chosen w/ paired accursed weapons and plasma pistol" in names
        assert any(a["max"] == 2 for a in chosen["alloc"])

    def test_accursed_cultists_torment_min(self, squads):
        build = squads["Accursed Cultists"]["builds"][0]
        mutant = build["models"][0]
        alloc = {a["name"]: a for a in mutant["alloc"]}
        assert alloc["Torment"]["min"] == 3
        assert alloc["Torment"]["max"] == 6
        assert alloc["Mutant"]["min"] == 5
        assert alloc["Mutant"]["max"] == 10

    def test_cultist_mob_champion_slot_default(self, squads):
        build = squads["Cultist Mob"]["builds"][0]
        champion = [m for m in build["models"] if m["name"] == "Cultist Champion"][0]
        slot = champion["slots"][0]
        choices = {c["name"]: c for c in slot["choices"]}
        assert choices["Autopistol"].get("default") is True
        assert "Bolt pistol" in choices

    def test_squads_resolve(self, csm_engine, squads):
        for name in squads:
            if name.startswith("_"):
                continue
            for t in TARGET_SAMPLES:
                res = csm_engine._best_squad_variant(name, csm_engine.resolve_target(t))
                assert res is not None, f"{name} {t}: did not resolve"
                assert res.get("ranged") or res.get("melee"), f"{name} {t}: empty"


class TestChaosTerminatorSquad:
    """Chaos Terminator Squad n=5: per-5 datasheet caps live in the alloc pool.

    Datasheet (verified against wahapedia 2026-08-14): per 5 models —
    1 heavy flamer OR reaper autocannon, any number combi-weapons,
    1 paired accursed weapons, up to 3 power fists, 1 chainfist.
    """

    def _model(self, squads, model_name) -> dict:
        build = squads["Chaos Terminator Squad"]["builds"][0]
        return next(m for m in build["models"] if m["name"] == model_name)

    def test_alloc_pool_caps(self, squads):
        m = self._model(squads, "Heavy weapon")
        assert m["count"] == 4
        alloc = {a["name"]: a for a in m["alloc"]}
        # 1 chainfist per 5
        assert alloc["Chainfist and combi-bolter"]["group_max"] == 1
        assert alloc["Chainfist and combi-weapon"]["group_max"] == 1
        # up to 3 power fists per 5, shared across both variants
        assert alloc["Power fist and combi-bolter"]["group_max"] == 3
        assert alloc["Power fist and combi-weapon"]["group_max"] == 3
        # 1 heavy weapon per 5; heavy model keeps Accursed weapon in melee
        hw = alloc["Heavy weapon"]
        assert hw["max"] == 1
        melee_slot = next(s for s in hw["slots"] if s["name"] == "Melee weapon")
        melee_choices = {c["name"] for c in melee_slot["choices"]}
        assert melee_choices == {"Accursed weapon"}
        # 1 paired accursed weapons per 5
        assert alloc["Paired accursed weapons"]["max"] == 1

    def test_champion_wargear_slot(self, squads):
        m = self._model(squads, "Terminator Champion")
        assert m["count"] == 1
        slot = m["slots"][0]
        names = {c["name"] for c in slot["choices"]}
        assert "Paired accursed weapons" in names
        # champion cannot add a chainfist or power fist beyond the pool caps
        assert not any("Chainfist" in n for n in names)
        assert not any("Power fist" in n for n in names)

    def test_resolve_caps_vs_targets(self, csm_engine):
        """Engine output respects the per-5 caps (structure, not numbers)."""
        for tname, exp in [("MEQ", (3, 0)), ("TEQ", (3, 0)), ("Knight", (2, 1))]:
            t = csm_engine.resolve_target(tname)
            res = csm_engine._best_squad_variant("Chaos Terminator Squad", t)
            assert res is not None
            pf = sum(1 for w in res["melee"] if "Power fist" in w.name)
            cf = sum(1 for w in res["melee"] if "Chainfist" in w.name)
            hw = sum(1 for w in res["ranged"] if w.name in ("Heavy flamer", "Reaper autocannon"))
            assert pf <= 3 and cf <= 1 and hw <= 1, f"{tname}: PF={pf} CF={cf} HW={hw}"
            assert (pf, cf) == exp, f"{tname}: got PF={pf} CF={cf}, expected {exp}"
